
#export ANYPOINT_USERNAME=<name>
#export ANYPOINT_PASSWORD=<password>
#export ANYPOINT_ORG="DWP"
#export ANYPOINT_ENV="Sandbox"
#export ANYPOINT_HOST="eu1.anypoint.mulesoft.com"

#script parameters (mandatory) 
MULE_BASE="/Users/adam.davis/other_applications/mule-4.1.5-RT1"
RUNTIME_NAME="ip-10-82-98-236.eu-west-2.compute.internal" 
SERVER_GROUP="myGroup-new" 

#proxy details (optional)
#PROXY_HOST=proxy.integr-dev.dwpcloud.uk
#PROXY_PORT=8080

ECHO ...start registration script

#get the token for registering the server 
ARM_TOKEN="$(anypoint-cli runtime-mgr server token)"
ECHO Registration token [$ARM_TOKEN]

#registered the runtime 
#${MULE_BASE}/bin/amc_setup -R eu1 -H $ARM_TOKEN $RUNTIME_NAME -P $PROXY_HOST $PROXY_PORT
${MULE_BASE}/bin/amc_setup -H $ARM_TOKEN $RUNTIME_NAME 

#add the proxy configuration to wrapper.conf. The integers identiofy the line numbers are deliberately lareg to avoid conflicts from the numbers generated by amc_setup
if [[ ! -z "$PROXY_HOST" ]]; then echo 'wrapper.java.additional.100=-Danypoint.platform.proxy_host='$PROXY_HOST >> ${MULE_BASE}/conf/wrapper.conf ; fi
if [[ ! -z "$PROXY_PORT" ]]; then echo 'wrapper.java.additional.101=-Danypoint.platform.proxy_port='$PROXY_PORT >> ${MULE_BASE}/conf/wrapper.conf ; fi

#get ther server id for the newly registered server 
SERVERID="$(anypoint-cli runtime-mgr server list -f ID,Name -o text | grep $RUNTIME_NAME | tr -dc '[:print:]' | sed 's/\[90m\[39m/ /g' | awk '{print $1}' )"

ECHO retrived SERVERID[$SERVERID] from RUNTIME_NAME [$RUNTIME_NAME]

if [[ -z "$SERVERID" ]]; then
	ECHO "Could not retreive Server ID, might be an issue creating server"
else

	#write the server id to a file so it can be reloaded on shutdown
	#cat "SERVERID="$SERVERID > ${MULE_BASE}/conf/env_vars

	#get the servergroup id
	SERVERGRPID="$(anypoint-cli runtime-mgr serverGroup list -f ID,Name -o text | grep $SERVER_GROUP | tr -dc '[:print:]' | sed 's/\[90m\[39m/ /g' | awk '{print $1}' )"
	ECHO retreived SERVERGRPID [$SERVERGRPID] from SERVER_GROUP [$SERVER_GROUP]


	#if the servergroup does not exist then create it
	if [[  -z "$SERVERGRPID" ]]; then
		anypoint-cli runtime-mgr serverGroup create $SERVER_GROUP 
		SERVERGRPID="$(anypoint-cli runtime-mgr serverGroup list -f ID,Name -o text | grep $SERVER_GROUP | tr -dc '[:print:]' | sed 's/\[90m\[39m/ /g' | awk '{print $1}' )"
		ECHO created SERVERGRPID [$SERVERGRPID]
	fi

	#should now have a SERVERGRPID
	if [[  -z "$SERVERGRPID" ]] ; then
		ECHO Something went wrong - SERVERGRPID [$SERVERGRPID]
	else
		ECHO Adding SERVERID [$SERVERID] to SERVERGRPID [$SERVERGRPID]
		#add the server to the server group 
		anypoint-cli runtime-mgr serverGroup add server $SERVERGRPID $SERVERID
	fi
fi

ECHO ...finish registration script
